### ISSUE TITLE
Error in rule compute_d4

### ISSUE THREAD

**Issue by weirdo-onlooker** [harvardinformatics/snpArcher#119]
I have just installed and executed snakemake -d .test/ecoli --cores 1 --use-conda according to the documentation. Now, I am encountering an error.
[Sat Aug 12 10:16:32 2023]
Error in rule compute_d4:
    jobid: 16
    input: results/GCA_000008865.2/bams/SAMN12676327_final.bam, results/GCA_000008865.2/bams/SAMN12676327_final.bam.bai
    output: results/GCA_000008865.2/callable_sites/SAMN12676327.mosdepth.global.dist.txt, results/GCA_000008865.2/callable_sites/SAMN12676327.per-base.d4, results/GCA_000008865.2/callable_sites/SAMN12676327.mosdepth.summary.txt
    log: logs/GCA_000008865.2/compute_d4/SAMN12676327.txt (check log file(s) for error details)
    conda-env: /ifs1/User/lengliang/yaozc/biosoft/snpArcher/.test/ecoli/.snakemake/conda/5cf955825d414ab876796f0a36009909_
    shell:
        mosdepth --d4 -t 1 results/GCA_000008865.2/callable_sites/SAMN12676327 results/GCA_000008865.2/bams/SAMN12676327_final.bam &> logs/GCA_000008865.2/compute_d4/SAMN12676327.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-08-12T101149.778379.snakemake.log

shell:
snakemake -d .test/ecoli --cores 1 --use-conda

What should I do to address this issue?

**Comment by cademirch** [comment]
Hi @weirdo-onlooker, can you pull the latest version of snpArcher? There was an issue with the latest version of mosdepth that is likely causing your issue.

**Comment by weirdo-onlooker** [comment]
Hi @cademirch, I downloaded snpArcher again by using "git clone https://github.com/harvardinformatics/snpArcher.git," but I still encountered the same issue. Could you please provide specific instructions on how to resolve this?

**Comment by cademirch** [comment]
@weirdo-onlooker Sorry that didn't work. Could you paste the contents of the log file: `.test/ecoli/logs/GCA_000008865.2/compute_d4/SAMN12676327.txt`? Could you also run the command `snakemake --version` and paste the output of that.

**Comment by weirdo-onlooker** [comment]
@cademirch The "compute_d4" file has not been generated in the folder GCA_000008865.2. And the Snakemake version used is 7.32.3.

**Comment by weirdo-onlooker** [comment]
@cademirch Thank you for your advice！ I changed 'mosdepth>=0.3.3' to 'mosdepth==0.3.3' in workflow/envs/cov_filter.yaml, and after trying again, it ran successfully！
