### ISSUE TITLE
environment can't be solved

### ISSUE THREAD

**Issue by Erythroxylum** [harvardinformatics/snpArcher#120]
Hello,
I am trying to run snpArcher on the FAS RC shared and intermediate partitions. I had successfully run the pipeline in the past, including the successful completion of building DAG jobs and creating conda environments, but now this error is being thrown. I cloned the repo yesterday. Python v.3.10.9

Here is the err output:
_________________________

Building DAG of jobs...
Creating conda environment workflow/envs/sambamba.yml...
Downloading and installing remote packages.
Environment for /n/holyscratch01/davis_lab/dwhite/snpArcher/workflow/rules/../envs/sambamba.yml created (location: .snakemake/conda/d4ce070fd79db94c65585010a0cbce48_)
Creating conda environment workflow/envs/fastq2bam.yml...
Downloading and installing remote packages.
Environment for /n/holyscratch01/davis_lab/dwhite/snpArcher/workflow/rules/../envs/fastq2bam.yml created (location: .snakemake/conda/bd19444950f6d7198b2ef10e58fef0ed_)
Creating conda environment workflow/modules/qc/envs/admixture.yml...
Downloading and installing remote packages.
Environment for /n/holyscratch01/davis_lab/dwhite/snpArcher/workflow/modules/qc/envs/admixture.yml created (location: .snakemake/conda/ad396f6e3cc1ce39333877d85180f4bf_)
Creating conda environment workflow/envs/bam2vcf.yml...
Downloading and installing remote packages.
Environment for /n/holyscratch01/davis_lab/dwhite/snpArcher/workflow/rules/../envs/bam2vcf.yml created (location: .snakemake/conda/abb557a3ad4a64770d7de92755c7727c_)
Creating conda environment workflow/modules/qc/envs/qc.yml...
Downloading and installing remote packages.
Environment for /n/holyscratch01/davis_lab/dwhite/snpArcher/workflow/modules/qc/envs/qc.yml created (location: .snakemake/conda/c7684bc535c943ed3559cb1e722b5d3d_)
Creating conda environment workflow/modules/qc/envs/subsample_snps.yml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /n/holyscratch01/davis_lab/dwhite/snpArcher/workflow/modules/qc/envs/subsample_snps.yml:
Command:
mamba env create --quiet --file "/n/holyscratch01/davis_lab/dwhite/snpArcher/.snakemake/conda/d31b712157bc989ecf6e7c76da46d03f_.yaml" --prefix "/n/holyscratch01/davis_lab/dwhite/snpArcher/.snakemake/conda/d31b712157bc989ecf6e7c76da46d03f_"
Output:
error    libmamba Could not open lockfile '/n/sw/Mambaforge-22.11.1-4/pkgs/cache/cache.lock'
error    libmamba Could not open lockfile '/n/sw/Mambaforge-22.11.1-4/pkgs/cache/cache.lock'
Could not solve for environment specs
Encountered problems while solving:
  - nothing provides libcblas >=3.8.0,<4.0a0 needed by bcftools-1.12-h3f113a9_0

The environment can't be solved, aborting the operation

__________________
Thanks for the help,
Dawson

**Comment by erikenbody** [comment]
You might also try a `mamba clean --all` while you're at it

It is odd its trying to create an env with both bcftools and libcblas, when
the yaml "subsamplesnps.yaml" only includes bcftools. I can't build an env
with those two either, but the environment from snparcher does work
Erik

**Comment by Erythroxylum** [comment]
OK, thanks for those suggestions. I will let you know how it goes.

-Dawson

**Comment by cademirch** [comment]
@Erythroxylum Were you able to resolve this?

**Comment by Erythroxylum** [comment]
Hello, Yes, it was resolved using `mamba clean --all` and rebuilding the
snpArcher environment.
