### ISSUE TITLE
Error with qc_admixture rule

### ISSUE THREAD

**Issue by ArsenaultResearch** [harvardinformatics/snpArcher#122]
Hi all, 
I have been trying to get the qc_admixture rule to successfully run but keep running into the same error (included below). I assume based on the error message that I need to adjust the chromosome names in some way. Do you all have any recommendations on how I can solve this error? Any assistance you can provide would be very appreciated. 
Thanks,
Sam

My chromosome names look like so: 
>contig_17684__unscaffolded
>PGA_scaffold2__141_contigs__length_26305080

Error message - 
[Tue Sep  5 16:24:25 2023]
rule qc_admixture:
    input: results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.bed, results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.bim, results/Lerg_assemblyV1/Q
C/Lerg_assemblyV1_E.fam
    output: results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.3.Q, results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.2.Q
    jobid: 0
    reason: Missing output files: results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.2.Q, results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.3.Q
    wildcards: refGenome=Lerg_assemblyV1, prefix=Lerg_assemblyV1_E
    resources: mem_mb=8000, mem_mib=7630, disk_mb=1000, disk_mib=954, tmpdir=/tmp

Activating conda environment: .snakemake/conda/5aabced42964e6ba7d428c98db59b6af_
****                   ADMIXTURE Version 1.3.0                  ****
****                    Copyright 2008-2015                     ****
****           David Alexander, Suyash Shringarpure,            ****
****                John  Novembre, Ken Lange                   ****
****                                                            ****
****                 Please cite our paper!                     ****
****   Information at www.genetics.ucla.edu/software/admixture  ****

Random seed: 43
Point estimation method: Block relaxation algorithm
Convergence acceleration algorithm: QuasiNewton, 3 secant conditions
Point estimation will terminate when objective function delta < 0.0001
Estimation of standard errors disabled; will compute point estimates only.
Invalid chromosome code!  Use integers.
[Tue Sep  5 16:24:25 2023]
Error in rule qc_admixture:
    jobid: 0
    input: results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.bed, results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.bim, results/Lerg_assemblyV1/Q
C/Lerg_assemblyV1_E.fam
    output: results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.3.Q, results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.2.Q
    conda-env: /n/holyscratch01/trible_lab/Users/sarsenault/snpArcher/.snakemake/conda/5aabced42964e6ba7d428c98db59b6af_
    shell:
        
        mv results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.bim results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.bim.orig
        paste <(cut -f 1 results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.bim.orig | sed 's/[^0-9]//g') <(cut -f 2,3,4,5,6 results/Lerg_asse
mblyV1/QC/Lerg_assemblyV1_E.bim.orig) >  results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.bim

        admixture results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.bed 2
        admixture results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.bed 3

        mv "Lerg_assemblyV1_E".2.* results/Lerg_assemblyV1/QC
        mv "Lerg_assemblyV1_E".3.* results/Lerg_assemblyV1/QC
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by erikenbody** [comment]
yeah that does seem to be the problem. We try to deal with it by deleting
all the characters in the contig names (with the sed command you can see
there), but it doesn't seem to have dealt with your contig names that are a
bit omplex. Can you run something like this, to show the contigs names in
the name repaired bim file you have?

cat results/Lerg_assemblyV1/QC/Lerg_assemblyV1_E.bim | cut -f 1 | sort |
uniq

let me know if this works -

Erik

**Comment by ArsenaultResearch** [comment]
Output is below. All seem to be numeric and I wasn't able to find any letters with grep. 

Output - 
10030
10100
10108
10116
10121
10139
10173
10268
10301
10399192094
10415
10438
10471
10481
10575
10627
10644
106861
106862
106864
10729
10745
107532
10793
10802
10821
10867
10872
109142
11006
11019
11051
11065
11100
11118
11190
11203
11247
11281
11316
11399295424
11460
11466
11511
115402
11576
11613
11696
117436745115
11774
118512
118513
11875
11884
118862
11910
11951
12043
12069
12103
12133
12167
122582
1239
12407
12468
12483
12489244263
12521
1253
12552
12572
12627
12676
1280
12802
12830
12850
12860
12881
12932
12965
130272
130273
13052
13066
131492
131493
13170
13232
13235
13240
13262
13271
13276
13290
13293
13322
13377
13402
13444
13513
13519118329
13578
13598
13602
13642
137552
13817
13849
13853
13854
1388
13897
13968
140042
14079
14097
14111
14114
14233
14235
14373
14377
144182
14463
14467761263
14492
14497
14502
14658
14669
146742
14731
14750
14758
14771
14821
1484
14845
14862
14864
1487
14883
14887
1490
14902
14953
14983
15000
15013
15021
15066
15086
15107
15127
15141
15179
15240
152552
15271
15275
15282
15284
15312
15337
15342
15349
15365
15382
15433
15450
15454
15514
15517
155211
15538
15539
15583
15587
15608
15608091670
15641
15670
15697
15707
15710
15748
15789
15806
15809
15816
15823
1586
15883
158952
158953
15899
15900
15903
15925
15940
15976
159822
15996
16005
16011
16014
16029
16049
16050
16053
16068
16082
16118
16149
16161
161742
16184
16187
16199
16200
16206
16207
16211
1623
16253
16255
16284
16300
16325
16350
16378113578
16427
16445
16454
16464
16479
16484
16489
16509
16536
16567
16586
16649
166641
16667
16698
16700
16718
16724
1678
16794
16803
16833
16886
16896
16905
16909
16919
16925
16937
16964
16993
17009
17010
17027
17056
17069
17082
17091
17102
17129
17132
17135
17154
17155
17160
17163
17164
17166
17168
17169
17170
17179
17181
17182
17183
17184
17187
17188
17189
17192
17193
17194
17195
17196
17198
17199
17201
17202
17203
17205
17207
17212
17213
17214
17217
17218
17220
17221
17225
17229
17230
17232
17234
17236
17243
17244
17246
17247
17250
17252
17253
17255
17256
17257
17259
17260
17262
17264
17265
17266
17267
17269
17270
17272
17273
17277
17279
17280
17281
17283
17284
17285
17286
17287
17289
17293
17294
17298
17303
17308
17309
17310
17311
17312
17315
17316
17317
17318
17322
17323
17325
17329
17332
17334
17336
17339
17341
17343
17346
17347
17347142411
17348
17356
17359
17361
17362
17365
17368
17371
17372
17373
17375
17379
17380
17386
17387
17388
17389
17397
17398
17401
17403
17404
17407
17408
17409
17412
17413
17417
17419
17420
17421
17423
17424
17426
17428
17432
17435
17442
17443
17444
17446
17447
17449
17452
17453
17460
17464
17467
17468
17470
17472
17477
17479
17480
17481
17482
17485
17486
17487
17488
17489
17494
17495
17496
17499
17504
17505
17506
17507
17511
17514
17517
17518
17519
175202
175203
17521
17524
17525
17526
17527
17528
17529
17531
17532
17535
17536
17537
17539
17543
17544
17545
17546
17548
17551
17552
17559
17560
17563
17566
17568
17572
17573
17576
17579
17584
17590
17593
17595
17597
17598
17608
17610
17615
17616
17620
17621
17623
17624
17625
17628
17631
17632
17633
17634
17635
17636
17638
17639
17648
17649
17650
17651
17654
17655
17657
17658
17660
17661
17662
17663
17665
17666
17672
17674
17675
17676
17681
17682
17683
17684
17686
17687
17690
17691
17692
17698
17699
17701
17702
17703
17704
17707
17710
17711
17714
17715
17716
17723
17727
17728
17730
17732
17735
17737
17738
17741
17743
17744
17748
17749
17753
17755
17756
17757
17758
17759
17763
17764
17767
17769
17772
177732
17774
17776
17777
17781
17783
177852
17790
17800
17807
17808
17811
17813
17817
17818
17821
17822
17825
17827
17828
17838
17841
17844
17845
17846
17848
1785
17853
17857
17859
17862
17863
17864
17866
17869
17870
17871
17874
17875
17876
17877
17882
17885
17886
17890
17891
17892
17893
17894
17900
17902
17904
17905
17907
17909
17911
17913
17914
17922
17924
17926
17927
17929
17930
17933
17936
17938
17941
17942
17943
17944
17946
17947
17948
17949
17953
17954
17958
17959
17960
17966
17970
17971
17974
17979
17982
17983
17984
17985
17990
17996
17997
17998
17999
18001
18002
18004
18005
18007
18008
18010
18012
18013
18016
18023
18024
18025
18026
18029
18030
18033
18036
18037
18040
18042
18045
18049
18052
18057
18059
18061
18062
18066
18068
18075
18077
18079
18084
18085
18087
18090
18091
18092
18093
18095
18096
18097
18104
18106
18107
18108
18111
18112
18113
18115
18116
18118
18121
18125
18126
18128
18130
18131
18134
18137
18140
18141
18142
18144
18145
18147
18149
18153
18154
18156
18157
18162
18165
18166
18167
18168
18171
18174
18175
18179
18183
18185
18186
18189
18193
18196
18199
18200
18203
18204
18206
18208
18209
18210
18212
18213
18217
18220
18221
18222
18226
18227
18228
18231
18234
18235
18237
18243
18244
18246
18254
18255
18256
18261
18262
18265
18267
18268
18269
1827
18270
18271
18272
18281
18283
18284
18289
18290
18291
18296
18297
18300
18302
18304
18306
18313
18314
18317
18319
18320
18321
18323
18324
18327
18330
18332
18336
18337
18338
18339
18347
18351
18352
18354
18357
18358
18359
18361
18369
18372
18374
18376
18379
18380
18381
18383
18388
18390
18391
18393
18396
18397
18399
18400
18404
18408
18410
18411
18413
18414
18417433226
18418
18419
18422
18423
18426
18427
18429
18431
18432
18437
18445
18449
18450
18451
18452
18453
18460
18461
18465
18467
18473
18476
18477
18480
18486
18490
18493
18494
18495
18499
1850
18502
18507
18509
18511
18514
18522
18523
18526
18529
18531
18534
18535
18537
18540
18546
18547
18548
18549
18552
18557
18565
18566
18567
18570
18572
18573
18575
18577
18579
18581
18584
18586
18589
18591
18595
18597
18598
18601
18602
18605
18607
18609
18610
18611
18614
18615
18622
18624
18626
18627
18628
18629
18634
18636
18638
18639
18640
18641
18646
18647
18651
18653
18656
18657
18658
18660
18661
18665
18667
18673
18675
18676
18679
18681
18683
18684
18687
18688
18691
18695
18697
18701
18703
18707
18709
18710
18715
18718
18719
18720
18721
18723
18725
18731
18734
18735
18737
18738
18739
18742
18745
18746
18753
18755
18756
18758
18760
18761
18763
18764
18765
18768
18769
18771
18772
18774
18780
18781
18782
18784
18785
18787
18788
18789
18790
18793
18795
18797
18798
18799
18802
18807
18810
18811
18820
18834
18839
18842
18844
18846
18850
18851
18852
18853
18855
18856
18859
18864
18865
18867
18868
18869
18870
18872
18873
18875
18877
18878
18880
18881
18887
18889
18890
18891
18896
18898
18902
18905
18906
18909
18913
18915
18917
18919
18920
18921
18923
18924
18925
18929
18932
18942
18945
18946
18949
18950
18951
18952
18953
18956
18958
18960
18961
18964
18966
18970
18971
18977
18978
18980
18981
18983
18984
18989
18992
18993
18994
18996
19003
19006
19008
19009
19010
19013
19016
19019
19025
19027
19029
19034
19036
19037
19038
19039
19041
19043
19045
19049
19050
19051
19052
19054
19055
19056
19058
19060
19062
19065
19067
19068
19071
19076
19077
19079
19082
19083
19089
19096
19100
19105
1910646579
19108
19110
19111
19112
19120
19121
19125
19128
19132
19133
19135
19142
19143
19150
19152
19154
19155
19156
19158
19161
19164
19165
19171
19172
19173
19174
19177
19179
19180
19181
19189
19193
19194
19195
19198
19202
19203
19207
19208
19211
19212
19213
19214
19216
19217
19218
19219
19220
19222
19223
19230
19231
19233
19234
19239
19244
19247
19255
19257
19261
19267
19276
19278
19282
19285
19287
19291
19297
19299
19300
19301
19302
19303
19304
19305
19306
19308
19309
19314
19316
19319
19320
19324
19325
19326
19327
19330
19331
19332
19336
19338
19340
19350
19353
19354
19356
19360
19363
19367
19370
19371
19375
19380
19381
19387
19392
19394
19396
19398
19399
19401
19403
19408
19415
19416
19422
19423
19424
19426
19428
19431
19432
19433
19434
19435
19437
19439
19444
19446
19447
19448
19450
19451
19454
19455
19457
19458
19461
19463
19468
19476
19478
19480
19481
19484
19485
19489
19490
19498
19499
19500
19501
19510
19512
19513
19514
19515
19516
19518
19519
19521
19522
19530
19533
19535
19536
19539
19542
19545
19547
19549
19551
19555
19557
19558
19560
19563
19572
19573
19575
19578
19579
19581
19583
19587
19589
19590
19592
19594
19595
19596
19598
19602
19603
19604
19607
19612
19613
19615
19618
19619
19622
19627
19630
19631
19634
19635
19638
19639
19641
19644
19645
19647
19648
19650
19652
19657
19661
19662
19663
19665
19666
19667
19672
19674
19675
19676
19677
19679
19685
19686
19691
19694
19695
19703
19708
19712
19714
19720
19721
19722
19723
19725
19727
19732
19735
19736
19737
19739
19740
19741
19747
19751
19752
19753
19756
19757
19762
19766
19770
19777
19778
19780
19781
19782
19785
19794
19799
19800
19804
19805
19806
19809
19810
19812
19814
19816
19818
19819
19822
19823
19825
19827
19829
19830
19831
19835
19837
19838
19843
19844
19845
19846
19848
19849
19850
19857
19858
19859
19860
19864
19868
19869
19870
19877
19880
19882
19884
19885
19886
19888
19889
19891
19892
19895
19897
19900
19902
19904
19905
19908
19909
19914
19919
19924
19927
19928
19933
19934
19940
19942
19945
19948
19949
19950
19951
19953
19955
19959
19963
19964
19967
19968
19969
19971
19972
19976
19981
19982
19984
19986
19990
19994
19995
19997
20001
20002
20005
20006
20009
20014
20016
20017
20020
20029
20033
20037
20038
20040
20042
20046
20050
20051
20055
20056
20060
20061
20064
20065
20070
20072
20073
20077
20080
20081
20082
20083
20084
20085
20089
20090
20091
20093
20097
20102
20103
20105
20106
20110
20112
20115
20119
20120
20121
20126
20127
20129
20131
20132
20133
20134
20139
20140
20143
20145
20146
20147
20148
20152
20158
20160
20170
20172
20179
20183
20185
20186
20187
20190
20193
20199
202
20201
20202
20205
20206
20207
20209
20211
20212
20217
20219
20221
20224
20228
20229
20235
20237
20239
20244
20246
20247
20248
20249
20250
20251
20261
20262
20264
20268
20271
20272
20273
20274
20277
20281
20284
20286
20287
20297
20301
20305
20306
20307
20308
20310
20313
20315
20316
20317
20319
20320
20321
20330
20335
20338
20340
20343
20345
20348
20350
20355
20357
20358
20360
20362
20365
20367
20368
20371
20372
20375
20376
20380
20382
20383
20384
20388
20389
20394
20396
20397
20398
20400
20404
20405
20407
20409
20413
20416
20418
20419
20420
20421
20422
20426
20428
20429
20432
20433
20439
20446
20447
20451
20452
20453
20455
20457
20458
20459
20460
20464
20465
20466
20468
20469
20471
20472
20473
20474
20475
20476
20478
20480
20481
20482
20487
20489
20490
20494
20495
20498
20500
20503
20504
20507
20508
20510
20511
20514
20517
20518
20521
20525
20526
20529
20530
20533
20536
20547
20550
20551
20553
20554
20555
20565
20567
20569
20571
20572
20573
20583
20585
20586
20592
20598
20601
20604
20606
20607
20608
20609
20616
20618
2062
20621
20622
20623
20625
20627
20628
20629
20631
20635
20641
20643
20644
20647
20649
20654
20656
20658
20660
20662
20670
20674
20679
20683
20691
20692
20693
20695
20697
20699
20700
20702
20705
20706
20708
20709
20710
20711
20712
20713
20717
20722
20723
20729
20731
20732
20733
20737
20738
20739
20741
20742
20748
20759
20766
20771
20772
20773
20774
20779
20780
20782
20788
20791
20797
20799
20801
20811
20813
20819
20822
20823
20828
20829
20834
20835
20837
20839
20842
20844
20845
20846
20847
20850
20856
20858
20861
20863
20866
20873
20878
20879
20880
20881
20883
20890
20891
20892
20893
20894
20896
20899
20900
20902
20903
20906
20911
20917
20920
20923
20929
20930
20931
20933
20934
20936
20941
20944
20945
20948
20950
20956
20957
20958
20959
20960
20961
20964
20966
20969
20970
20971
20972
20974
20977
20981
20983
20984
20985
20987
20989
20996
21000
21003
21004
21005
21006
21009
21010
21014
21019
21024
21025
21027
21029
21031
21040
21041
21042
21043
21047
21051
21052
21061
21062
21063
21064
21066
21070
21071
21073
21075
21076
21080
21081
21083
21088
21091
21094
21098
21100
21103
21104
21105
21106
21107
21109
21110
21119
21122
21123
21124
21125
21127
21130
21134
21135
21136
21137
21140
21143
21144
21146
21148
21149
21154
21159
21160
21162
21166
21170
21173
21174
21175
21178
21184
21185
21186
21190
21191
21193
21199
21201
21202
21205
21211
21214
21217
21220
21221
21223
21225
21227
21231
21233
21234
21235
21241
21246
21255
21256
21257
21258
21263
21267
21274
21275
21276
21277
21279
21280
21284
21286
21288
21290
21291
21292
21296
21306
21308
21310
21311
21314
21316
21322
21324
21325
21330
21339
21347
21349
21352
21353
21354
21361
21365
21369
21373
21374
21378
21382
21387
21388
21396
21397
21398
21405
21406
21407
21411
214126305080
21414
21420
21426
21429
21431
21432
21433
21434
21439
21440
21442
21443
21456
21469
21470
21480
21492
21501
21507
21514
21517
21522
21527
21528
21529
21532
21535
21537
21541
21542
21543
21544
21545
21549
21552
21553
21556
21558
21559
21561
21564
21570
21571
21573
21574
21575
21578
21579
21581
21582
21583
21587
21589
21590
21593
21609
21610
21615
21616
21635
21649
21655
21662
21666
21668
21672
21678
21679
21694
21696
21699
21721
21728
21732
21739
21741
21743
21746
21754
21755
21760
21765
21766
21772
21784
21790
21806
21813
21814
2182
21822
2183
21850
21871
21890
21894
21895
21896
21904
21920
21921
21925
21932
21933
21938
21948
21951
21952
21953
22017
22023
22031
22032
22040
22051
22052
22063
22073
22074
22076
22078
22079
22082
22088
22093
22097
22110
22131
22146
22162
22163
22164
22172
22185
22186
22198
22208
22228
22238
22266
22267
22280
22285
22286
22324
2233
22332
22346
22349
22350
22369
22370
22414
22421
22448
22455
22458
22474
22478
22491
22493
22494
22501
22549
22554
22555
22562
22567
22573
22590
22599
22613
22622
22639
2264
22645
22657
22667
22677
22681
22684
22708
22725
22744
22757
22763
22770
22792
22795
22827
22829
22837
22848
22849
22851
22864
22883
22884
22886
22887
22901
22911
22916
22921
22926
22928
22940
22947
22956
22957
22965
22979
22983
22985
22988
22992
23001
23028
23060
23076
23077
23083
23088
23099
23111
23125
23139
23140
23143
23144
23159
23162
23163
23164
23165
23166
23175
23185
23204
23225
23244
23248
23279
23300
23301
23305
23310
23315
23318
23342
23359
23364
23381
23432
23475
23480
23498
23523
23524
23555
23576
23630
23657
23660
23675
23677
23690
23721
23728
23743
23746
23748
23750
23759
23777
23779
23788
23789
23795
23805
23807
23811
23815
23817
23819
23824
23826
23827
23837
23840
23842
23845
23846
23856
23859
23860
23861
23868
23870
23876
2388
23883
23889
23902
23903
23911
23914
23925
23926
23941
23945
23947
23951
23958
23961
23964
23977
23978
23983
24000
24003
24007
24011
24024
24031
24036
24037
24042
24047
24055
24064
24068
24070
24090
24100
24103
24105
24109
24112
24123
24124
24131
24134
24135
24138
24143
24158
24169
24173
24176
24179
24194
24200
24208
24214
24215
24216
24219
24222
24230
24231
24234
24235
24243
24245
24252
24255
24266
24269
24275
24282
24283
24289
24291
24295
24299
24302
24307
24308
24309
24311
24319
24324
24334
24346
24347
24350
24360
24361
24364
24371
24375
24389
24391
24399
24403
24404
24415
24416
24418
24419
24420
24421
24426
24427
2507
25212
255
2693
2694
2715
30022
30023
3091
3112
3188
3230
3264
3532
3556
3637
36542
36543
3764
3772
38316628596
3846
3903
3988
4000
4060
4065
410515682291
423
4273
430
4301
4333
4349
4378
4404
4417
4459
4497
4503
4520
4531
4549
4632
4639
46982
46983
4727
4791
4797
4822
4876
4939
5057
5103
51072
5171
5198
529
5299
5385
5424
5488
55572
55692
56112855327
5687
5785
5830
5873
588
59522
5979
6151
6154
6166
6217
6315
6319
6385
6444
6447
6476
65211233901
6559
6612
6620
6711
6718
6740
6797
683
6841
6845
6849
6884
68862
68863
6960
7088
7112
7115
7136
717
722
7232
7252
7401
74311650447
7432
7478
7519
7523
7532
755
7570
7574
7657
7706
7722
7736
7809
7839
7880
7890
793
7949
796
7990
7993
7995
8005
8048
8082
8143
8152
8167
8177
820
8290
8292
8309
8311
8316
8339
8343
8387
8452
8464
8507
8533
8536
858
8612
8632
8709
87192
87194
8725
8747
882
884
88522
88523
8875
88811584615
8882
8884
8887
8923
8993
9051
9080
9154
9156
9287
9290
9317
9329
9347
9441
9449288374
9502
9504
9564
9574
9595
9597
9603
96113
9616
9696
9741
975
9780
97891
97892
9794
9810
9819
9844
988
9927
9999

**Comment by tsackton** [comment]
This one is a puzzle.

Can you check to make sure you have no duplicate contig names post-processing? Theoretically I guess that might lead to the same error as non-numeric chromosome names. Google is not very informative on this point, unfortunately.

Also, perhaps it is worth trying to run admixture outside of snakemake, just to confirm the same error message.

Finally, you can hack things to remove the admixture plot if necessary - in the QC module Snakefile, comment out the admixture files in the qc_plots rule, and in the qc_dashboard_interactive.Rmd script comment out the admixture section at the bottom. That should let you get a QC plot without the admixture results.

**Comment by cademirch** [comment]
@ArsenaultResearch, were you able to resolve this?

**Comment by ArsenaultResearch** [comment]
Hi, apologies for the delay. I was able to hack out the admixture bit as Tim suggested and the rest ran correctly. Thanks for the help on this!
