### ISSUE TITLE
Error in rule dedup

### ISSUE THREAD

**Issue by weirdo-onlooker** [harvardinformatics/snpArcher#123]
@erikenbody When I run Snakemake, one of the steps encountered an error, and both the error message and the server administrator indicated that the tmp cache was full. 

How can I modify the tmp directory? 

Note that after modifying the cache directory in the config.yaml file, there was no change in the behavior.

**Comment by tsackton** [comment]
Hi,

Which rule encountered the error? Not every job uses big_tmp and it is possible that if your system tmp directory is on the smaller size, you are running into an issue with a rule that we have not modified to use the big_tmp path in the config.

Can you share the error message and any other logs you have?

**Comment by weirdo-onlooker** [comment]
I'm sorry, I forgot to copy the error message: 
Error in rule dedup:
jobid: 9
input: results/GCF_030020395.1/bams/preMerge/pangolin/PNG1.bam, results/GCF_030020395.1/bams/preMerge/pangolin/PNG1.bam.bai
output: results/GCF_030020395.1/bams/pangolin_final.bam, results/GCF_030020395.1/bams/pangolin_final.bam.bai
log: logs/GCF_030020395.1/sambamba_dedup/pangolin.txt (check log file(s) for error details)
conda-env: /sdc1/home/hk/yaozc/snpArcher-main/.snakemake/conda/0068d55d38ca6ffb2c000410df01fcd8_
shell:
sambamba markdup -t 1 results/GCF_030020395.1/bams/preMerge/pangolin/PNG1.bam results/GCF_030020395.1/bams/pangolin_final.bam 2> logs/GCF_030020395.1/sambamba_dedup/pangolin.txt
(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.

The pangolin.txt file has been overwritten, and the original message roughly means "no space left." 

How can I set dedup to big_tem?

**Comment by tsackton** [comment]
I created a branch with these changes, can you test and see if this fixes the issue for you?

You will need to update snpArcher to use the `dedup-bigtmp` branch, either by: running `git pull; git checkout dedup-bigtmp` in your snpArcher directory, or by running `git clone -b dedup-bigtmp https://github.com/harvardinformatics/snpArcher/` in a new directory.

**Comment by cademirch** [comment]
Curious if @tsackton's fix worked for you @weirdo-onlooker?

**Comment by cademirch** [comment]
Closing this - @weirdo-onlooker, please reopen if you still have trouble.
