### ISSUE TITLE
Unintended whitespace in fastq paths.

### ISSUE THREAD

**Issue by ChabbyTMD** [harvardinformatics/snpArcher#141]
Hi Team,

I'm using SNPArcher on a resequencing dataset from NCBI SRA. I downloaded the SRA run table for 2 samples for testing purposes and made the necessary modifications as per the documentation. Upon execution of the pipeline I obtain the following error where whitespace is being inserted into the file paths of the read files. 

`Building DAG of jobs...
File path ' results/data/fastq/ GCF_900626175.2 / SAMN19471810 / SRR14708202 _1.fastq.gz ' starts with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path ' results/data/fastq/ GCF_900626175.2 / SAMN19471810 / SRR14708202 _1.fastq.gz ' ends with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path ' results/data/fastq/ GCF_900626175.2 / SAMN19471810 / SRR14708202 _2.fastq.gz ' starts with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path ' results/data/fastq/ GCF_900626175.2 / SAMN19471810 / SRR14708202 _2.fastq.gz ' ends with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
MissingInputException in rule fastp in file /home/trevor/Desktop/snpArcher/workflow/rules/fastq.smk, line 34:
Missing input files for rule fastp:
	output: results/GCF_900626175.2/filtered_fastqs/SAMN19471810/SRR14708202_1.fastq.gz, results/GCF_900626175.2/filtered_fastqs/SAMN19471810/SRR14708202_2.fastq.gz, results/GCF_900626175.2/summary_stats/SAMN19471810/SRR14708202.fastp.out
	wildcards: refGenome=GCF_900626175.2, sample=SAMN19471810, run=SRR14708202
	affected files:
     	results/data/fastq/ GCF_900626175.2 / SAMN19471810 / SRR14708202 _1.fastq.gz
     	results/data/fastq/ GCF_900626175.2 / SAMN19471810 / SRR14708202 _2.fastq.gz
`

I'm not sure why this is happening.

**Comment by ChabbyTMD** [comment]
Hi @cademirch, I'll try this and get back to you. Thank you.

**Comment by cademirch** [comment]
> Hi @cademirch, I'll try this and get back to you. Thank you.

@ChabbyTMD, did this work for you?

**Comment by cademirch** [comment]
Great, glad it worked!
