### ISSUE TITLE
Error in rule create_cov_bed: ModuleNotFoundError: No module named 'pyd4'

### ISSUE THREAD

**Issue by Erythroxylum** [harvardinformatics/snpArcher#144]
Hello, I just set up snakemake and executed the ecoli test command within a login node and then again with the test partition on the FASRC server. The error is:

Traceback (most recent call last):
  File "/n/holyscratch01/davis_lab/dwhite/snpArcher/.test/ecoli/.snakemake/scripts/tmpb53k8wei.create_coverage_bed.py", line 5, in <module>
    from pyd4 import D4File,D4Builder
ModuleNotFoundError: No module named 'pyd4'
[Wed Dec 13 10:30:55 2023]
Error in rule create_cov_bed:
    jobid: 14
    input: results/GCA_000008865.2/summary_stats/all_cov_sumstats.txt, results/GCA_000008865.2/callable_sites/all_samples.d4
    output: results/GCA_000008865.2/callable_sites/ecoli_test_callable_sites_cov.bed
    conda-env: /n/holyscratch01/davis_lab/dwhite/snpArcher/.test/ecoli/.snakemake/conda/e6e860e6c3364a4f25a50109432a6090_

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-12-13T091938.314670.snakemake.log

-The .snakemake directory to get the complete log does not exist. Please let me know if there are any logs you would like to see. Thanks for your attention.

**Comment by cademirch** [comment]
What was your snakemake command? Did you include --use-conda?

**Comment by cademirch** [comment]
Unfortunately I wasn't able to recreate this by pulling a fresh copy of the repo and running the test. Can you try that?

**Comment by Erythroxylum** [comment]
I had cloned the repo again and got the same error before posting this
issue, but I will try again.

**Comment by cademirch** [comment]
Ah okay, sorry. Can you post the snakemake output when it tries to create
the conda env?

**Comment by Erythroxylum** [comment]
Here is the main output. I will have to wait to rerun before I can get any
more of the log files.

**Comment by Erythroxylum** [comment]
I am rebuilding the conda environment and I see that I was activating the
snakemake environment instead of the 'snparcher' environment, which could
be an issue. In either case, the 'pyd4' package is not listed as an
installed package with the following command:
(mamba create -c conda-forge -c bioconda -n snparcher snakemake)
But I will try again in the snparcher env instead of snakemake

**Comment by tsackton** [comment]
snakemake will build its own conda environment for each rule; all you need in the snakemake/snparcher env is snakemake itself.

**Comment by Erythroxylum** [comment]
Hello again,
The same error appeared. Here is the snakemake log:

**Comment by tsackton** [comment]
I think this has something to do with the mamba/conda setup. I cannot replicate this error either, even on the same cluster. Can you perhaps list all the commands you are running exactly as you typed them? Not just the snakemake command, but basically everything you type from when you log on to the cluster to when you get the error message?

**Comment by Erythroxylum** [comment]
Well, thank you both for your attention. I am not sure what changed, but it
has now completed the job two times. You can close the issue. Here is the
code:

srun --pty -p test --mem 10000 -c 1 -t 120 /bin/bash

module load python

mamba activate snparcher

snakemake -d .test/ecoli --cores 1 --use-conda

**Comment by tsackton** [comment]
Reopening this issue because I suspec this has to do with a conflict between the python version that is specified in https://github.com/harvardinformatics/snpArcher/blob/main/workflow/envs/cov_filter.yml and the python version the user builds snpArcher against. 

I suspect we need to remove the python from the cov_filter.yml

**Comment by Dictionary2b** [comment]
I had the same error on the previous attempt. It was solved by manually installing the pyd4 package to the env. The alternative is pinning the Python version to 3.10 since the default in my system was 3.11, where snparcher would have difficulty installing pyd4. I haven't test the second solution.

**Comment by tito-abbo** [comment]
I am also having this issue but I am unable to install pyd4 manually as others have suggested to solve the issue. According to the documentation I could find, the only way to install pyd4 is with pip but I get the error:  Building wheel for pyd4 (pyproject.toml) ... error                            
  error: subprocess-exited-with-error                                           
                                                                                
  × Building wheel for pyd4 (pyproject.toml) did not run successfully.          
  │ exit code: 1                                                                
  ╰─> [36 lines of output]                                                      
      <string>:7: SetuptoolsDeprecationWarning: The test command is disabled and
 references to it are deprecated.                                               
      !!                                                                        
 I don't think my institutions HPC has a rust compiler installed so I can't compile the package from source either. Thus, I am stuck.
