### ISSUE TITLE
support snakemake >= 8.0

### ISSUE THREAD

**Issue by cademirch** [harvardinformatics/snpArcher#149]
Snakemake made some pretty big changes in their newest release. Seems to break a few things we depend on #147. Using this to document and fix

**Comment by cademirch** [comment]
Snakemake 8 migration docs: https://snakemake.readthedocs.io/en/latest/getting_started/migration.html#migrating-to-snakemake-8

**Comment by tsackton** [comment]
In addition, reconfigure our profile setup to support slurm using the "workflow profile" setup.
