### ISSUE TITLE
job execution failed at concat_gvcfs

### ISSUE THREAD

**Issue by Erythroxylum** [harvardinformatics/snpArcher#153]
Hello,
The pipeline failed during concat_gvcfs, but many of the jobs for this rule had been completed successfully, so I am not sure what killed the pipeline. Can you please take a look at the err file?
[err_ERY335-1.txt](https://github.com/harvardinformatics/snpArcher/files/14089237/err_ERY335-1.txt)

Just in case this is part of the problem, I would like to explain that these data are a mix of SRA and local fastqs, and among the SRA data they are a mix of WGS together with a large majority of targeted-capture sequences for 500 genes. My goal is phylogenetic inference based on the 500 genes. My plan is to filter the final vcf to only include the coordinates of the target exons.

Thank you for your help,
Dawson

**Comment by tsackton** [comment]
Hi Dawson,

I don't see anything in the error output that could explain why the run stopped. It is possible that some local cluster issues are responsible. Usually in this case the easiest thing to do is just restart the pipeline, so I would try that first.

Tim

**Comment by Erythroxylum** [comment]
Hi Tim,
After the first restart, the pipeline started at the very beginning, fastp and accessing SRA data, then failed at an early step. I changed a few SRA samples in the samplesheet and started it again and it ran all the way up until the QC modules and failed there. So, FYI, this is my second dataset that has failed on the QC modules because of huge memory requests.
Thanks for your attention here. You can close this issue.
-Dawson
