### ISSUE TITLE
encountered same error when setting cores and executing snpArcher on my local machine

### ISSUE THREAD

**Issue by yuan-circle-long** [harvardinformatics/snpArcher#158]
the environment is ok when using "_**snakemake -d .test/ecoli --cores 1 --use-conda**_" to test.

I tried to set up the cores using "_**snakemake --cores 8 --use-conda**_" and encountered an error.
![image](https://github.com/harvardinformatics/snpArcher/assets/135928920/44d60c21-e863-46bc-b3b2-b0c6f39e4d8a)
l also executed my own data, and the same error was happened.
The error message relates to three files: reference.smk, common.smk, and Snakefile. However, I did not change these files.  l only changed the parameters of resources.ymal.

The code is on the main disk and the sequencing files are on another disk. For testing purposes, I chose three samples to build the sample table.
![image](https://github.com/harvardinformatics/snpArcher/assets/135928920/714ac6d2-938f-45c4-a085-e1a3f84a9141)

Best wishes

**Comment by yuan-circle-long** [comment]
![image](https://github.com/harvardinformatics/snpArcher/assets/135928920/9f5cee8c-e424-41fb-aa8f-6ec3d005ca16)
Building DAG of jobs...
InputFunctionException in rule download_reference in file /home/aiworkstation/snpArcher/workflow/rules/reference.smk, line 3:
Error:
  IndexError: list index out of range
Wildcards:
  refGenome=ref
Traceback:
  File "/home/aiworkstation/snpArcher/workflow/rules/common.smk", line 79, in get_ref

**Comment by tsackton** [comment]
This looks like an error parsing your sample sheet. Can you confirm that your sample sheet is comma-separated and looks the same as the example sample sheet?

**Comment by yuan-circle-long** [comment]
Thanks for your help very much! Compared with the example sample sheet, the **ref path** in my sample sheet is a directory not a fasta file. l modify the sample sheet and the code runs no problem. 
![image](https://github.com/harvardinformatics/snpArcher/assets/135928920/05382ad8-5d94-40a7-9cc3-d7ddce11c5fe)

**Comment by yuan-circle-long** [comment]
Sorry to bother you again.

In my project, the cores number is set to 48, and the memory is 100000. But using the **top** command shows the cpu used is just 100%，is this condition is normal？ 

![image](https://github.com/harvardinformatics/snpArcher/assets/135928920/7745ae6a-50de-40de-a3a5-f8bbef777b5f)
**the resource file**
![image](https://github.com/harvardinformatics/snpArcher/assets/135928920/37dffda6-450e-4fd0-aebb-e08b2b8cbe26)
**the cpu used** 

![image](https://github.com/harvardinformatics/snpArcher/assets/135928920/0e332338-a7ff-4a48-af2a-5c9be26fb8bf)
![image](https://github.com/harvardinformatics/snpArcher/assets/135928920/5364a786-19ac-48b1-b15b-f16c2781ac55)
**My computer hardware**
About my data, the reference genome is about 8GB, and each sample is about 3GB. l used the GBS sequencing method.

**Comment by yuan-circle-long** [comment]
Memory usage seems to be normal now.
![image](https://github.com/harvardinformatics/snpArcher/assets/135928920/b0ae6db2-a3c6-40e7-8454-2c05ac6ef5ac)

**Comment by cademirch** [comment]
Hi @yuan-circle-long, glad its working as expected.
