### ISSUE TITLE
option for allele merging - VCF2TileDBException

### ISSUE THREAD

**Issue by gghill** [harvardinformatics/snpArcher#163]
Hi there,
Thanks for developing and supporting such an efficient and self-contained pipeline! My most recent run (94 samples) failed at gvcf2DB with an error (log [0647.txt](https://github.com/harvardinformatics/snpArcher/files/14521134/0647.txt)):

`terminate called after throwing an instance of 'VCF2TileDBException'
  what():  VCF2TileDBException : Incorrect cell order found - cells must be in column major order. Previous cell: [ 33, 487571965 ] current cell: [ 33, 487571965 ].
The most likely cause is unexpected data in the input file:
(a) A VCF file has two lines with the same genomic position
(b) An unsorted CSV file
(c) Malformed VCF file (or malformed index)`

A quick [search](https://gatk.broadinstitute.org/hc/en-us/community/posts/4403240487451-GenomicsDBImport-variants-have-the-same-position-in-Gvcf-file) suggests this is a common issue with GATK that can be addressed by running `bcftools norm` to merge the alleles at the same position prior to GATK. Is there any way to do this or otherwise address this issue in the snpArcher workflow (such as by manually fixing the vcfs and handing them back to the pipeline)? Thanks for your help, very excited to be close to a finished run and first results.

**Comment by gghill** [comment]
Hi Cade,
Thanks for the quick response. From the documentation you posted, the only sticking point I can see (as a definite non-expert) is the removal of "exact" duplicates, maybe inexact matches are slipping through but somehow still too overlapping for GATK? I have tried another run with the branch version of the workflow, as you suggested, and while the error is different, the problem seems similar ([log1](https://github.com/harvardinformatics/snpArcher/files/14535613/0690.txt), [log2](https://github.com/harvardinformatics/snpArcher/files/14535616/0686.txt)) as now in DB2vcf I get an error concerning overlapping variants: 

`terminate called after throwing an instance of 'VariantQueryProcessorException'
  what():  VariantQueryProcessorException : Unhandled overlapping variants at columns 519969767 and 519969768 for row 10`

followed (and preceded) by a number of lines of 
`Benchmark: unable to collect cpu and memory benchmark statistics`
but that doesn't seem as related (though it is the first time I've seen it).

It seems like it doesn't fail for all imported .tar files, the same genome is being used for all samples, and there hasn't been any indication so far that individual samples are problematic (though I'm not sure whether at this stage the input .tars are still individuals). All samples are present in the DB_mapfile. Please let me know if you have any advice or there is additional information I can provide.

**Comment by cademirch** [comment]
Shame that didn't work, looks like it moved the error one step downstream. It will be hard to debug this out without access to the problematic gVCFs unfortunately. I may suggest deleting or removing the problem gVCFs and letting the workflow remake them, perhaps something weird happened for a few while generating them. 

@tsackton Have you seen this before?

**Comment by tsackton** [comment]
I have seen this once or twice before, usually associated though with some kind of file corruption. I'd suggest deleting the g.vcf and the interval g.vcfs and see if that helps. If not, it might reflect some problems with the merge step we'd need to investigate. You can also check and see if the file looks complete.

**Comment by gghill** [comment]
Just wanted to check back in to let you know after a couple false starts and a week or two of run time, the run completed using the bcftools_norm branch and a complete fresh run (changed the reference genome name to encourage it to start from scratch). The results look great, the interactive QC html is super useful and I look forward to digging in further. Thanks for your help :)

**Comment by cademirch** [comment]
Thanks for the update @gghill. Glad it worked. @tsackton should we merge the bcftools_norm? Seems like it might have been helpful in this case?

**Comment by tsackton** [comment]
Yes, that seems like a good idea
