### ISSUE TITLE
Warning rule qc_qc_plots stops the pipeline

### ISSUE THREAD

**Issue by ffertrindade** [harvardinformatics/snpArcher#166]
I'm facing a situation where this rule qc_qc_plots runs correctly, creating the qc_dashboard_interactive.html file, but apparently cannot rename/move the location of this file.

> [Fri Mar  1 06:25:55 2024]
> rule qc_qc_plots:
>     input: results/EryCar/QC/eryth_17ind_20240125.eigenvec, results/EryCar/QC/eryth_17ind_20240125.eigenval, results/EryCar/QC/eryth_17ind_20240125.idepth,>
>     output: results/EryCar/QC/eryth_17ind_20240125_qc.html
>     jobid: 143
>     reason: Missing output files: results/EryCar/QC/eryth_17ind_20240125_qc.html; Input files updated by another job: results/EryCar/QC/eryth_17ind_2024012>
>     wildcards: refGenome=EryCar, prefix=eryth_17ind_20240125
>     resources: tmpdir=/var/tmp/pbs.9754.blmsvfhpc04.itv.local, mem_mb=2000, mem_mib=1908
> 
> Activating conda environment: .snakemake/conda/2163aaf3dd1da2622e91d2dc19ffce36_
> Waiting at most 5 seconds for missing files.
> MissingOutputException in rule qc_qc_plots in file /mnt/gen/opt/softwares/snpArcher/workflow/modules/qc/Snakefile, line 164:
> Job 143  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the >
> results/EryCar/QC/eryth_17ind_20240125_qc.html
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message

Since the workflow is in a different folder (to which I don't have total access) where my output files are located, I think the pipeline can't move/rename the QC HTML. Is that correct? I can request the administrator to manually give me access, but this isn't the best solution considering other people from my institution will use the pipeline. Do you have any suggestions on that? Maybe creating this HTML directly in the expected output folder?

Thanks!

**Comment by cademirch** [comment]
Thanks Fer, I'm looking into this now.

**Comment by cademirch** [comment]
Hi @ffertrindade this issue should be fixed in #167. Will be merged soon.
