### ISSUE TITLE
Question: Can I disable MarkDuplicates?

### ISSUE THREAD

**Issue by Erythroxylum** [harvardinformatics/snpArcher#172]
Hello,
I am interested in using this pipeline with GBS data, but the identical start and end sequences make most reads get flagged as duplicates. Is there a simple way to disable mark duplicates or would it require significant alterations to downstream code?
Thanks!

**Comment by cademirch** [comment]
It might be easier to tell downstream tools (haplotypecaller) to ignore the duplicate flag in the bams. I'll look into this today

**Comment by erikenbody** [comment]
Do you know how this usually gets handled in GBS pipelines? If the only switch is to remove mark duplicates, it would be easy-ish to have it as an option. In the short term, you could also just replace [this line](https://github.com/harvardinformatics/snpArcher/blob/730475ffdb1c0c4729b24e26fb4eb82a54ba3635/workflow/rules/fastq2bam.smk#L49) with something like ```cp {input.bam} {output.dedupBam} 2> {log}``` then your bam file wouldn't have any duplicates

**Comment by Erythroxylum** [comment]
GATK is not a usual approach for GBS pipelines, but my understanding is
that typically no deduplication is done because there is no good method to
detect dups.

**Comment by cademirch** [comment]
Working on adding this.

**Comment by cademirch** [comment]
As a temp solution, if you're not using GATK and just need the BAMS w/o duplicates marked, you can try:
```
snakemake --until dedup --no-temp <... other options>
```

**Comment by cademirch** [comment]
This will be added in #173, feel free to pull the branch to test it out

**Comment by Erythroxylum** [comment]
Hi @cademirch , 
Wow, thanks for your prompt attention! I have cloned the branch. Can you please explain what flags I need to use to keep dups?

**Comment by cademirch** [comment]
@Erythroxylum You'll need to set `mark_duplicates` to `False` in the `config.yaml`. Also when you run snakemake, add the `--notemp` option.

**Comment by tsackton** [comment]
merged with #173

**Comment by Erythroxylum** [comment]
Hi Cade et al.:
FYI, the mark_duplicates flag is absent from the snpArcher/config/config.yaml. I can, however, see it in the .test/ecoli/config/config.yaml. I just appended it to my main config/config.yaml, hoping that will work.

**Comment by cademirch** [comment]
Oops. Thanks for pointing that out, I’ll fix soon.
