### ISSUE TITLE
KeyError while setting up dry run

### ISSUE THREAD

**Issue by spilornis-ng** [harvardinformatics/snpArcher#180]
Hi!
While setting up a dry run to check if everything looks fine, I get the following error.

KeyError in file /mnt/hdd/Naman/Naman_wgs_trial/snparcher_trial/snpArcher/workflow/rules/common.smk, line 25:
'resource_config'
  File "/mnt/hdd/Naman/Naman_wgs_trial/snparcher_trial/snpArcher/workflow/rules/common.smk", line 25, in <module>

I was wondering if there is something wrong in the way I have setup my config.yaml and sample sheet.

![image](https://github.com/harvardinformatics/snpArcher/assets/81860485/cb5299a7-a4a3-47d2-8728-c02a430bb194)

**Comment by cademirch** [comment]
Hi @spilornis-ng, this will be fixed shortly.
