### ISSUE TITLE
Error in rule fastp

### ISSUE THREAD

**Issue by spilornis-ng** [harvardinformatics/snpArcher#183]
Hi!
Thanks for fixing the previous issue! 
However, when I am running the code now I get the following error. The log files generated are also empty. 

Error in rule fastp:
    jobid: 29
    input: /mnt/hdd/Naman/Naman_wgs_trial/2_clean/Turdus_simillimus_bourdilloni_B0937_R1_paired.fq.gz, /mnt/hdd/Naman/Naman_wgs_trial/2_clean/Turdus_simillimus_bourdilloni_B0937_R2_paired.fq.gz
    output: results/GCA_013186435.1_ASM1318643v1_genomic/filtered_fastqs/Turdus_simillimus_bourdilloni_B0937/1_1.fastq.gz, results/GCA_013186435.1_ASM1318643v1_genomic/filtered_fastqs/Turdus_simillimus_bourdilloni_B0937/1_2.fastq.gz, results/GCA_013186435.1_ASM1318643v1_genomic/summary_stats/Turdus_simillimus_bourdilloni_B0937/1.fastp.out
    log: logs/GCA_013186435.1_ASM1318643v1_genomic/fastp/Turdus_simillimus_bourdilloni_B0937/1.txt (check log file(s) for error details)
    conda-env: /mnt/hdd/Naman/Naman_wgs_trial/snparcher_trial/trial_project/.snakemake/conda/f949ce1fdb59cb745f9cb17349cd25d7_
    shell:
        fastp --in1 /mnt/hdd/Naman/Naman_wgs_trial/2_clean/Turdus_simillimus_bourdilloni_B0937_R1_paired.fq.gz --in2 /mnt/hdd/Naman/Naman_wgs_trial/2_clean/Turdus_simillimus_bourdilloni_B0937_R2_paired.fq.gz --out1 results/GCA_013186435.1_ASM1318643v1_genomic/filtered_fastqs/Turdus_simillimus_bourdilloni_B0937/1_1.fastq.gz --out2 results/GCA_013186435.1_ASM1318643v1_genomic/filtered_fastqs/Turdus_simillimus_bourdilloni_B0937/1_2.fastq.gz --thread 1 --detect_adapter_for_pe -j /dev/null -h /dev/null 2> results/GCA_013186435.1_ASM1318643v1_genomic/summary_stats/Turdus_simillimus_bourdilloni_B0937/1.fastp.out > logs/GCA_013186435.1_ASM1318643v1_genomic/fastp/Turdus_simillimus_bourdilloni_B0937/1.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Fri Apr 19 02:18:12 2024]
Removing output files of failed job fastp since they might be corrupted:
results/GCA_013186435.1_ASM1318643v1_genomic/summary_stats/Turdus_simillimus_bourdilloni_B0937/1.fastp.out

**Comment by cademirch** [comment]
Hmm sorry about that. From what you've pasted in I can't quite figure out what's going on. You can try pulling the PR I've linked which should make sure any errors from fastp make it to the logfile.

**Comment by spilornis-ng** [comment]
Hi!
I was able to resolve this. Closing this issue!
