### ISSUE TITLE
Rule Exception in rule bam2gvcf - Attribute error

### ISSUE THREAD

**Issue by spilornis-ng** [harvardinformatics/snpArcher#187]
![image](https://github.com/harvardinformatics/snpArcher/assets/81860485/0bbf26b4-ef44-4ac6-8820-df03cb698e1b)

Hi! 
I am getting the above error while running the workflow. I checked the config.yaml in default profile and can't really pin-point the issue.
Any help will be great!

Thanks!

**Comment by cademirch** [comment]
What was your command line? You need to make sure to have the --profile specified

**Comment by spilornis-ng** [comment]
` snakemake -s ./snpArcher/workflow/Snakefile -d ./IBB_trial/ --cores 48 --conda-frontend conda --use-conda`

Used this as the command line. I thought that by default it uses Default profile, so didn't specify it particularly. Will try running it with --profile flag.

**Comment by spilornis-ng** [comment]
This worked. Thanks! I am closing this now.
