### ISSUE TITLE
fastq.smk

### ISSUE THREAD

**Issue by atigano** [harvardinformatics/snpArcher#196]
Hi,
I've run snpArcher on a dataset successfully before. Then, I started to work on a new dataset and nothing is working anymore, I did exactly the same everything, after copying and updating the config and sample list files. Tried to run the first dataset and it doesn't work anymore either. I've downloaded the newest version with Snakemake 8 and I get the same error below. The test dataset works though! 

KeyError in file /gpfs/fs7/grdi/genarcc/wp3/annat/snpArcher/workflow/rules/fastq.smk, line 45:
'sort_reads'
  File "/gpfs/fs7/grdi/genarcc/wp3/annat/snpArcher/workflow/Snakefile", line 7, in <module>
  File "/gpfs/fs7/grdi/genarcc/wp3/annat/snpArcher/workflow/rules/fastq.smk", line 45, in <module>

Do you have any idea what might be going on? Here I attach my more recent sample file.
Thanks!
[samples_chum_snparcher_cov1.8.csv](https://github.com/harvardinformatics/snpArcher/files/15355290/samples_chum_snparcher_cov1.8.csv)

**Comment by cademirch** [comment]
Hi @atigano, this is because we added the option to sort reads based on read name recently. It seems like the config option "sort_reads" is missing from your config file.

**Comment by atigano** [comment]
Thank you! It's working now.
