### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by OsmanthusZhang** [harvardinformatics/snpArcher#197]
Hi, when i running snpArcher, the run result shows error:

AttributeError in file /data_32T/yaozc/snpArcher_1/workflow/rules/fastq.smk, line 6:
'Workflow' object has no attribute 'default_remote_prefix'
  File "/data_32T/yaozc/snpArcher_1/workflow/rules/fastq.smk", line 6, in <module>

here is my command:
`nohup snakemake --use-conda --core 16 > logs/PNG_sequencing_20240523_1.log 2>&1 &
tail -f  logs/PNG_sequencing_20240523_1.log`

I checked the file fastq.smk and there are no syntax errors. Then i  reset the file about snpArcher, it also have some problem:

subprocess.CalledProcessError: Command 'conda info --json' returned non-zero exit status 127.

here is my command:

`snakemake -d .test/ecoli --core 12 --use-conda`

Thanks

**Comment by cademirch** [comment]
Please check your snakemake version and that you have pulled the latest commits from the snparcher repo.

**Comment by OsmanthusZhang** [comment]
Thanks for your adivce. Which snakemake version do you suggest I download?
