### ISSUE TITLE
Error with running the command 

### ISSUE THREAD

**Issue by AmitSharma267** [harvardinformatics/snpArcher#200]
Hi there,

when we are trying to run the command we are encountering this error. 

<img width="1171" alt="image" src="https://github.com/harvardinformatics/snpArcher/assets/158214436/ce8d2ac2-38a4-452b-986f-9068d940d5fe">

the sample sheet is set up as:
```
BioSample,refGenome,refPath,fq1,fq2
SS3_S143,sclscl_ref,/home/sharma267/project1/GCF_000146945.2_ASM14694v2_genomic.fna,/home/sharma267/project1/SS3_S143_L008_R1_001.fastq.gz,/home/sharma267/project1/SS3_S143_L008_R2_001.fastq.gz
```

and config.yaml looks like this:
<img width="841" alt="image" src="https://github.com/harvardinformatics/snpArcher/assets/158214436/bb168292-2e79-4ff5-bc7e-5a6ff90d2448">

Also tried putting the reference genome and its path to the config.yaml file but it gives the same error. 
 
We are unable to figure out root of the problem. Could you please help me here?
Please let me know if more information is needed. 
Thanks in advance.
Amit

**Comment by erikenbody** [comment]
Looks like you are missing the “run” column form the sample sheet

**Comment by AmitSharma267** [comment]
That error is gone. Thank you
