### ISSUE TITLE
Error in rule sort_gatherVcfs

### ISSUE THREAD

**Issue by daicy527** [harvardinformatics/snpArcher#201]
Dear snparcher developers,

I encounter an error rule sort_gatherVcfs when I run the pipeline. The information is as follows:
============================================
Checking the headers and starting positions of 1634 files
[E::hts_idx_load3] Could not load local index file 'results/GCA_013397395.1/vcfs/intervals/filtered_L1020.vcf.gz.tbi' : Too many open files
Failed to open results/GCA_013397395.1/vcfs/intervals/filtered_L1020.vcf.gz: could not load index
[W::bgzf_read_block] EOF marker is absent. The input may be truncated
[E::bcf_hdr_read] Failed to read BCF header
Could not read VCF/BCF headers from -
Cleaning
==================
I have tried to delete and regenerate this file, but the error remains.
Many thanks
Trying

**Comment by tsackton** [comment]
You may be running into a limit with the number of open files on your system. You can try setting this with `ulimit -n` to see if that helps.

**Comment by daicy527** [comment]
> You may be running into a limit with the number of open files on your system. You can try setting this with `ulimit -n` to see if that helps.

Thank you Tim, it works.
