### ISSUE TITLE
Error running the code

### ISSUE THREAD

**Issue by AmitSharma267** [harvardinformatics/snpArcher#203]
Hello there,

I am having issues with running the code.

My sample sheet looks like this-
```
SS3_S143,ss3_lib,sclscl_ref,/home/sharma267/project1/GCF_000146945.2_ASM14694v2_genomic.fna,1,/home/sharma267/project1/SS3_S143_L008_R1_001.fastq.gz,/home/sharma267/project1/SS3_S143_L008_R2_001.fastq.gz
```

I tried running this command
```
snakemake -s /home/sharma267/snpArcher/workflow/Snakefile -d /home/sharma267/project1 --cores 4
```
It shows me this error

<img width="1225" alt="image" src="https://github.com/harvardinformatics/snpArcher/assets/158214436/4ae32f68-3183-467d-b083-d545544785ab">
<img width="1225" alt="image" src="https://github.com/harvardinformatics/snpArcher/assets/158214436/b09143bd-e8e7-46e4-9357-c64c6ea68de0">

Please let me know if more information is needed. 
Thanks in advance.
Amit

**Comment by cademirch** [comment]
Hi Amit,

Can you please paste or upload the log files specified in the rule error messages?

**Comment by AmitSharma267** [comment]
Hi Cade,

I says I do not have those files. (base) 

[sharma267@ap2002 ~]$ cat logs/sclscl_ref/index_ref/log.txt
cat: logs/sclscl_ref/index_ref/log.txt: No such file or directory
(base) [sharma267@ap2002 ~]$ cat logs/sclscl_ref/fastp/SS3_S143/1.txt
cat: logs/sclscl_ref/fastp/SS3_S143/1.txt: No such file or directory
(base) [sharma267@ap2002 ~]$ cat logs/sclscl_ref/genmap/log.txt
cat: logs/sclscl_ref/genmap/log.txt: No such file or directory
(base) [sharma267@ap2002 ~]$

**Comment by cademirch** [comment]
Amit, those files should be in the project directory: /home/sharma267/project1

**Comment by AmitSharma267** [comment]
I tried looking it. 

the log.txt file in index_ref says-

(base) [sharma267@ap2002 sclscl_ref]$ ls
download_ref  fastp  genmap  index_ref
(base) [sharma267@ap2002 sclscl_ref]$ cd index_ref
(base) [sharma267@ap2002 index_ref]$ ls
log.txt
(base) [sharma267@ap2002 index_ref]$ nano log.txt
(base) [sharma267@ap2002 index_ref]$ 

  GNU nano 5.6.1                                             log.txt                                                       
/usr/bin/bash: line 2: bwa: command not found
<img width="1236" alt="image" src="https://github.com/harvardinformatics/snpArcher/assets/158214436/213b1c76-a2df-42fa-be7a-52d0fc79a8f1">

the log.txt file in genmap says-

(base) [sharma267@ap2002 sclscl_ref]$ ls
download_ref  fastp  genmap  index_ref
(base) [sharma267@ap2002 sclscl_ref]$ cd  genmap
(base) [sharma267@ap2002 genmap]$ ls
log.txt
(base) [sharma267@ap2002 genmap]$ nano log.txt

  GNU nano 5.6.1                                             log.txt                                                       
/usr/bin/bash: line 2: genmap: command not found
<img width="1236" alt="image" src="https://github.com/harvardinformatics/snpArcher/assets/158214436/05a6607e-3084-4006-a8ba-e72803f45307">

while 1.txt file in fastp is vacant

<img width="1236" alt="image" src="https://github.com/harvardinformatics/snpArcher/assets/158214436/8d96b19d-4d48-4b01-be19-dcf29db11cdf">

log.txt in download_ref seems same.

(base) [sharma267@ap2002 sclscl_ref]$ ls
download_ref  fastp  genmap  index_ref
(base) [sharma267@ap2002 sclscl_ref]$ cd download_ref 
(base) [sharma267@ap2002 download_ref]$ ls
log.txt
(base) [sharma267@ap2002 download_ref]$ nano log.txt

<img width="1236" alt="image" src="https://github.com/harvardinformatics/snpArcher/assets/158214436/c896edcf-a79d-4214-8525-ee474e6aaf5f">

Please le me know if more information needed

**Comment by cademirch** [comment]
Can you try modifying your command to this:
`snakemake -s /home/sharma267/snpArcher/workflow/Snakefile --profile /home/sharma267/snpArcher/profiles/default -d /home/sharma267/project1 --cores 4`

**Comment by AmitSharma267** [comment]
Thank you! that worked. 
Appreciate the help!
