### ISSUE TITLE
oxford nanopore data

### ISSUE THREAD

**Issue by jasonwjohns** [harvardinformatics/snpArcher#212]
Hi guys,

I have some ONP resequencing data that I would like to run through snpArcher if possible. I've generated .bams deduplicated with sambamba outside of snpArcher, as ONP data are single end and I wasn't sure how that would be handled. Additionally, the alignment step was taking a super long time. I would now like to generate vcfs for these few samples and run them through the rest of the pipeline. I tried manually making a results directory then a subdirectory with the name of the reference, then dropping the bams and genome files in. When I go to submit the job I get the following error:

```
Using workflow specific profile /hb/groups/bernardi_lab/Jason_OPOR/snpArcher/profiles/slurm for setting default command line arguments.
snpArcher: Using Snakemake 8.10.7
Building DAG of jobs...
InputFunctionException in rule fastp in file /hb/groups/bernardi_lab/Jason_OPOR/snpArcher/workflow/rules/fastq.smk, line 31:
Error:
  ValueError: can only convert an array of size 1 to a Python scalar
Wildcards:
  refGenome=DFU_1000_500_no_contaminants.fasta
  sample=DFU_Big_file_pc2_36_37_38_39
  run=DFU
Traceback:
  File "/hb/groups/bernardi_lab/Jason_OPOR/snpArcher/workflow/rules/common.smk", line 218, in get_reads
  File "/hb/home/jwjohns/.conda/envs/snparcher/lib/python3.11/site-packages/pandas/core/base.py", line 418, in item (rule fastp, line 68, /hb/groups/bernardi_lab/Jason_OPOR/snpArcher/workflow/rules/fastq.smk)
```

I realize that the solution to this may be quite complicated, especially since ONP data are single end reads, but I thought I would drop a note to see if you guys have dealt with this before and have a quick fix. If it's at all complicated I'll probably just run these few samples through the same workflow (haplotypecaller, filtering, QC, etc.), but manually - especially since it's only a few files. Let me know what you think. Thanks!

**Comment by tsackton** [comment]
I'm not sure that GATK is the best method to use for calling SNPs with ONT data, to be honest. Something like [pepper](https://github.com/kishwarshafin/pepper) is probably going to work a lot better. While we have aspirations to eventually support this within the snpArcher framework, it is a long term goal likely dependent on further funding for development, so unfortunately not something we are likely to be able to implement soon.

**Comment by jasonwjohns** [comment]
That makes sense, Tim. Thank you for the advice!
