### ISSUE TITLE
workflow continuity

### ISSUE THREAD

**Issue by austinchipps** [harvardinformatics/snpArcher#220]
Hi ya'll,

I'm having some trouble with the workflow running continuously, and what I mean by that is: the workflow isn't continuously submitting new jobs when others complete. I'm working on my university's HPC, and I didn't have this issue ~2 months ago when I was testing the workflow with a smaller dataset. In that time, I've expanded my dataset and had to delete/reinstall snparcher. 

What I'm seeing is that I'll submit the snakemake command from a headnode in a tmux session, jobs are submitted, and the tmux session sits idle with no job completion updates, etc. Jobs will finish and then nothing happens. Then for example, after fastp jobs have finished, I have to resubmit the snakemake command to prompt the submission of bwa-mem jobs. When I was originally running the workflow, the tmux session would have periodical updates of jobs completing and new jobs being submitted. Additionally, I would be notified in tmux if any of the jobs failed. I'm not finding any information in log files that would suggest things are failing, and I'm unsure if this is a snakemake issue or rather something with our university HPC. 

Please let me know if you need any additional information, and thank you in advance for your time. 

Austin

**Comment by cademirch** [comment]
Hi Austin,

Thanks for the report. Unfortunately this a known Snakemake issue, but has been difficult to fully fix.

https://github.com/snakemake/snakemake/issues/759
https://github.com/snakemake/snakemake/issues/1248

I've been working on some Snakemake issues again, so I'll put this one on the top of my list! Going to close this here since this is on Snakemake.

**Comment by austinchipps** [comment]
Ahh ok ok, good to know. Thank you for your response, Cade!

Austin
