### ISSUE TITLE
Conda error?

### ISSUE THREAD

**Issue by austinchipps** [harvardinformatics/snpArcher#222]
Hi ya'll,

I'm stuck at the create_gvcf_intervals and create_db_intervals step. I have attached the log file and the slurm log file. Looks like an issue with something in a conda environment? I'm not sure how to best proceed, but my initial thought is to re-create my snparcher environment. 

Thank you for your time,

Austin

[335302.log](https://github.com/user-attachments/files/17013601/335302.log)
[log.txt](https://github.com/user-attachments/files/17013610/log.txt)

**Comment by cademirch** [comment]
Hm, this is a new one to me. Looks like some sort of python path issue? I think recreating envs is a good place to start.

**Comment by austinchipps** [comment]
No such luck. I re-created the snparcher environment with 

mamba create -c conda-forge -c bioconda -n snparcher "snakemake>=8" "python==3.11.4"

and receive the same error messages. Unsure how to proceed - any suggestions?

Thank you in advance!

**Comment by tsackton** [comment]
Hi Austin,

What OS are you using?

Also, does it help if you build the snparcher environment with python 3.10?

**Comment by austinchipps** [comment]
Hi Tim,

Our university HPC has the RedHat Enterprise Linux 8 Operating System. I tried to build the snparcher with python 3.10 but then get a chain of confilcts: 

Could not solve for environment specs
The following packages are incompatible
├─ python 3.10  is requested and can be installed;
└─ snakemake >=8  is not installable because there are no viable options
   ├─ snakemake [8.0.0|8.0.1|...|8.9.0] would require
   │  └─ snakemake-minimal [8.0.0.* |8.0.1.* |...|8.9.0.* ], which requires
   │     ├─ python >=3.11,<3.13  but there are no viable options
   │     │  ├─ python [3.11.0|3.11.1|...|3.12.6] conflicts with any installable versions previously reported;
   │     │  └─ python [3.12.0rc3|3.13.0rc1|3.13.0rc2] would require
   │     │     └─ _python_rc, which does not exist (perhaps a missing channel);
   │     └─ snakemake-interface-report-plugins >=1.0.0,<2.0.0 , which requires
   │        └─ python >=3.11.0,<4.0.0  but there are no viable options
   │           ├─ python [3.11.0|3.11.1|...|3.12.6] conflicts with any installable versions previously reported;
   │           └─ python [3.12.0rc3|3.13.0rc1|3.13.0rc2], which cannot be installed (as previously explained);
   └─ snakemake 8.11.2 would require
      └─ snakemake-minimal 8.11.2.* , which does not exist (perhaps a missing channel). 

Can snparcher use older versions of snakemake..? 

-Austin

**Comment by tsackton** [comment]
Ah, right, forgot about the snakemake 8 issue. Hmm. 

Did you remove the snakemake-generated environments when you rebuilt the snparcher environment? If there is anything in `ddnA/work/achipp1/Sulawesi_phylogeny/snpArcher-test/Sulawesi_setup/project_runFULL/.snakemake/conda/` it might still be causing problems.

**Comment by cademirch** [comment]
> No such luck. I re-created the snparcher environment with 
> 
> 
> 
> mamba create -c conda-forge -c bioconda -n snparcher "snakemake>=8" "python==3.11.4"
> 
> 
> 
> and receive the same error messages. Unsure how to proceed - any suggestions?
> 
> 
> 
> Thank you in advance!

If you're getting error messages trying to create this environment, then I suspect something is funky with your conda and/or python installs. Perhaps try reinstalling conda?

**Comment by austinchipps** [comment]
Hi @cademirch, 

That was exactly what I had to do - still not sure what the underlying issue was, but a fresh conda install has things working again. 

Thank you!

Austin
