### ISSUE TITLE
file.rename() in qc.dashboard.render fails across partitions

### ISSUE THREAD

**Issue by tsackton** [harvardinformatics/snpArcher#90]
If you have snpArcher set up so that the workflow is in, say, a home directory and the working directory is in a different partition, then file.rename() will fail with the "Invalid cross-device link" error message. This seems to be a limitation of the file.rename() function when trying to move files between partitions. 

While a minor issue since the qc html still remains in the original scripts directory in this case, it would be worth adding some robustness here. The best option is probably to use file.copy instead, and then remove the original file once file.copy succeeds.

Adding this as an issue for documentation and tracking.

**Comment by cademirch** [comment]
Fixed in #167
