### ISSUE TITLE
java space/memory issue for db2vcf step

### ISSUE THREAD

**Issue by subirshakya** [harvardinformatics/snpArcher#91]
the dv2vcf step fails for only the last set of db intervals (originally had 6 intervals fail to finish and subsequently after filtering genome for small scaffolds (<1000 bp) had 1 interval fail to finish). The error that genomicsdbimport generates says out of space error (i used a tmp directory in the working directory so should not run out of memory unless genomicsdbimport uses a different tmp directory (i can can be set with --tmpdir option). The log file of one of these is included below. There was also a notice of a fatal error with java.

[0130.txt](https://github.com/harvardinformatics/snpArcher/files/10483103/0130.txt)

**Comment by cademirch** [comment]
Hi @subirshakya, sorry this got missed. How much space is available on the filesystem you're working on? And how big are the gvcfs?
